CC=g++
CFLAGS=-c -Wall
LDFLAGS=-framework OpenGL -lglfw3
SOURCES=main.cpp vao.cpp scene.cpp program.cpp shader.cpp application.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=main

all: $(SOURCES) $(EXECUTABLE)


$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	@rm -f *.o 