CC=g++
CFLAGS=-c -Wall
LDFLAGS=-lGLEW -lglut -framework OpenGL
SOURCES=main.cpp vao.cpp scene.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=main

all: $(SOURCES) $(EXECUTABLE)


$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@
