CC=g++
CFLAGS=-c -Wall -std=c++11
LDFLAGS=-lglfw3 -framework OpenGL
SOURCES=$(wildcard *.cpp) $(wildcard *.c)
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=main

all: $(SOURCES) $(EXECUTABLE)


$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	@rm -f *.o 
